spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hwj01/config
          username: hwj01
          password: githubmima123
          basedir: D:/qinlongworkspace/config/basedir
  rabbitmq:
    host: 192.168.99.100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh