spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: adminroot
    password: klby_ql9980
    url: jdbc:mysql://rm-8vb9448x23pq5zu6gio.mysql.zhangbei.rds.aliyuncs.com:3306/logistics_bak20190713?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/

